name: Build Executable and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 检查 main.py 和 prompt.txt 是否存在
        shell: bash
        run: |
          if [ ! -f "main.py" ]; then
            echo "错误: main.py 不存在!"
            exit 1
          fi
          if [ ! -f "files/prompt.txt" ]; then
            echo "错误: files/prompt.txt 不存在!"
            exit 1
          fi

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 验证已安装的依赖
        run: |
          pip list

      - name: 使用 Nuitka 打包可执行文件
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: app
          include-data-dir: |
            ./files=files
          include-modules: |
            pygments
            httpx
            rich
            python-dotenv

      - name: 列出打包后的文件
        run: |
          ls -R build/

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} 构建
          path: |
            build/
          include-hidden-files: true