name: Build Executable and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Check if main.py and prompt.txt exist
        shell: bash
        run: |
          if [ ! -f "main.py" ]; then
            echo "Error: main.py does not exist!"
            exit 1
          fi
          if [ ! -f "Functions/prompt.txt" ]; then
            echo "Error: Functions/prompt.txt does not exist!"
            exit 1
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install your Dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify Installed Dependencies
        run: |
          pip list

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: app
          include-data-files: |
            ./files/prompt.txt=files/prompt.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/
          include-hidden-files: true
